folder_name: "net_0"
model_type: "PDE_Z1"

n_node_types: 5
node_type_names:
  - poisson
  - oscillator
  - low_pass
  - high_pass
  - moving_avg
n_node_types_per_type: [5, 0, 4, 5, 6]

filter_length_max: 5
n_frames: 200
dt: 1.0