folder_name: "net_0"

simulation:
  n_node_types: 5
  node_type_names:
    - poisson
    - oscillator
    - low_pass
    - high_pass
    - moving_avg
  n_node_types_per_type: [5, 0, 4, 5, 6]
  filter_length_max: 5
  n_frames: 200
  dt: 1.0

model:
  model_type: "PDE_Z1"

training:
  n_runs: 2
  noise_level: 1.0E-4